### ISSUE TITLE
Is the notes completed?

### ISSUE THREAD

**Issue by vasanthgk02** [SHINEILCHI/WebDevNotes#1]
I have completed the course and now finding a way to lookback what I have learnt in a quick manner. Is your notes fully completed?

**Comment by SHINEILCHI** [comment]
Hi @vasanthgk02,

I haven't been able to update this repository for quite some time and I'm pretty much sure that this aren't full of the notes that I had.

Although, I do have it on my Notion notes. You can send me your email and I'll send you a copy. I would also update this repository in the coming days to help others.

Thanks for reminding!

**Comment by vasanthgk02** [comment]
Hi,
Thanks for you response. I have attatched my email below!

Mail : ***@***.***

Thanks

**Comment by SHINEILCHI** [comment]
Hi @vasanthgk02,
[Web Development Notes.txt](https://github.com/SHINEILCHI/WebDevNotes/files/9775002/Web.Development.Notes.txt)


I can't see your email here in this comment but here's the file in .txt format. This is all that I have noted in the 2021 Web Development course from Angela Yu in Udemy.
